name: Deploy Node.js app to AlmaLinux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Deploy to VPS
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          # Ensure the SSH directory exists
          mkdir -p ~/.ssh

          # Store the private SSH key securely
          echo "${{ secrets.DEPLOY_SSH_KEY }}" | base64 --decode > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Add the VPS to known hosts
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

          # Start SSH agent and add the key (fix for "error in libcrypto")
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

          # Connect to VPS and deploy
          ssh -o StrictHostKeyChecking=no vefrmeistari@${{ secrets.VPS_IP }} << 'EOF'
            set -e

            # Mark the repository as safe
            git config --global --add safe.directory /var/www/_blogCronicasDelVejerete

            # Navigate to project
            cd /var/www/_blogCronicasDelVejerete

            # Create backup before pulling changes
            backup_file="backup_$(date +%Y%m%d_%H%M%S).tar.gz"
            tar -czf "\$backup_file" .
            echo "Backup created: \$backup_file"

            # Reset local repo safely
            git fetch origin main
            git reset --hard origin/main

            # Install dependencies and build
            npm install
            NODE_ENV=production npm run build

            # Restart app using PM2
            pm2 start npm --name "nextjs-app" -- start -- -p 3001 || pm2 restart nextjs-app
          EOF
