name: Deploy Blog App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Deploy to VPS
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          # 1. Set up SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

          # 2. Connect to VPS
          ssh -i ~/.ssh/id_ed25519 vefrmeistari@${{ secrets.VPS_IP }} << 'EOF'
            set -e

            cd /var/www/_blogCronicasDelVejerete

            git config --global --add safe.directory /var/www/_blogCronicasDelVejerete
            git fetch origin main
            git reset --hard origin/main

            npm install
            NODE_ENV=production npm run build

            pm2 start npm --name "nextjs-app" -- start -- -p 3001 || pm2 restart nextjs-app
          EOF
